[package]
name = "domeneshop_cli"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
public-ip = "0.2.2"
tokio = { version = "1.34.0", features = ["macros"] }
reqwest = { version = "0.11.22", features = ["json"] }
serde_json = "1.0.108"
serde = {version = "1.0.193", features = ["derive"]}
chrono = "0.4.32"
domeneshop_client = { git = "https://github.com/Arthyon/domeneshop_client.git", rev = "1441350b218d826d8ebe947f5305b1cee99c4acb" }
simple-log = "1.6.0"
